repos:
  - repo: local
    hooks:
      - id: check-yaml
        name: Check YAML
        entry: python -m pre_commit_hooks.check_yaml
        language: system
        types: [yaml]
      - id: check-toml
        name: Check TOML
        entry: python -m pre_commit_hooks.check_toml
        language: system
        types: [toml]
      - id: trailing-whitespace
        name: Trim trailing whitespace
        entry: python -m pre_commit_hooks.trailing_whitespace_fixer
        language: system
        types: [text]
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: Fix final newlines
        entry: python -m pre_commit_hooks.end_of_file_fixer
        language: system
        types: [text]
